# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=jcroql
version: 1

env:
  - GO111MODULE=on

before:
  hooks:
    - task setup
    # - ./scripts/completions.sh
    # - ./scripts/manpages.sh

snapshot:
  name_template: "{{ incpatch .Version }}-next"

report_sizes: true

metadata:
  mod_timestamp: "{{ .CommitTimestamp }}"

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
      - ppc64
    goarm:
      - "7"
    ignore:
      - goos: windows
        goarch: arm
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s -w -X {{.ModulePath}.version={{.Version}} -X {{.ModulePath}}.commit={{.Commit}} -X {{.ModulePath}}.date={{ .CommitDate }} -X {{.ModulePath}}.treeState={{ .IsGitDirty }}

universal_binaries:
  - replace: false

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  use: github
  groups:
    - title: "New Features"
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 100
    - title: "Security updates"
      regexp: '^.*?sec(\([[:word:]]+\))??!?:.+$'
      order: 150
    - title: "Bug fixes"
      regexp: '^.*?(fix|refactor)(\([[:word:]]+\))??!?:.+$'
      order: 200
    - title: Dependency updates
      regexp: '^.*?(feat|fix|chore)\(deps\)!?:.+$'
      order: 300
    - title: "Documentation updates"
      regexp: ^.*?docs?(\([[:word:]]+\))??!?:.+$
      order: 400
    - title: "Build process updates"
      regexp: ^.*?(build|ci)(\([[:word:]]+\))??!?:.+$
      order: 400
    - title: Other work
      order: 9999

dockers:
  - image_templates:
      - "ghcr.io/jippi/scm-engine:v{{ .Version }}-amd64"
    dockerfile: Dockerfile.release
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=io.artifacthub.package.readme-url=https://raw.githubusercontent.com/jippi/scm-engine/main/README.md"
      - '--label=io.artifacthub.package.maintainers=[{"name":"Christian Winther","email":"scm-engine@jippi.dev"}]'
      - "--label=io.artifacthub.package.license=MIT"
      - "--label=org.opencontainers.image.description=Easy .env files"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/amd64"
  - image_templates:
      - "ghcr.io/jippi/scm-engine:v{{ .Version }}-arm64"
    dockerfile: Dockerfile.release
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=io.artifacthub.package.readme-url=https://raw.githubusercontent.com/jippi/scm-engine/main/README.md"
      - '--label=io.artifacthub.package.maintainers=[{"name":"Christian Winther","email":"scm-engine@jippi.dev"}]'
      - "--label=io.artifacthub.package.license=MIT"
      - "--label=org.opencontainers.image.description=Easy .env files"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/arm64"
    goarch: arm64

docker_manifests:
  - name_template: "ghcr.io/jippi/scm-engine:v{{ .Version }}"
    image_templates:
      - "ghcr.io/jippi/scm-engine:v{{ .Version }}-amd64"
      - "ghcr.io/jippi/scm-engine:v{{ .Version }}-arm64"
  - name_template: "{{ if not .IsNightly }}ghcr.io/jippi/scm-engine:latest{{ end }}"
    image_templates:
      - "ghcr.io/jippi/scm-engine:v{{ .Version }}-amd64"
      - "ghcr.io/jippi/scm-engine:v{{ .Version }}-arm64"
  - name_template: "{{ if .IsNightly }}ghcr.io/jippi/scm-engine:nightly{{ end }}"
    image_templates:
      - "ghcr.io/jippi/scm-engine:v{{ .Version }}-amd64"
      - "ghcr.io/jippi/scm-engine:v{{ .Version }}-arm64"

archives:
  - name_template: >-
      {{- .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end -}}
    format_overrides:
      - goos: windows
        format: zip
    builds_info:
      group: root
      owner: root
    files:
      - README.md
      - LICENSE
      # - completions/*
      # - manpages/*

brews:
  - repository:
      owner: jippi
      name: homebrew-tap
    directory: Formula
    goarm: "7"
    homepage: https://github.com/jippi/scm-engine
    description: Makes working with .env files easy
    license: MIT
    test: |
      system "#{bin}/scm-engine -v"
    dependencies: []
    # extra_install: |-
    #   bash_completion.install "completions/scm-engine.bash" => "scm-engine"
    #   zsh_completion.install "completions/scm-engine.zsh" => "_scm-engine"
    #   fish_completion.install "completions/scm-engine.fish"
    #   man1.install "manpages/scm-engine.1.gz"

aurs:
  - homepage: https://github.com/jippi/scm-engine
    description: Makes working with .env files easy
    maintainers:
      - "Christian Winther <scm-engine at jippi dot dev>"
    license: MIT
    private_key: "{{ .Env.AUR_KEY }}"
    git_url: "ssh://aur@aur.archlinux.org/scm-engine-bin.git"
    package: |-
      # bin
      install -Dm755 "./scm-engine" "${pkgdir}/usr/bin/scm-engine"

      # license
      install -Dm644 "./LICENSE" "${pkgdir}/usr/share/licenses/scm-engine/LICENSE"

      # completions
      # mkdir -p "${pkgdir}/usr/share/bash-completion/completions/"
      # mkdir -p "${pkgdir}/usr/share/zsh/site-functions/"
      # mkdir -p "${pkgdir}/usr/share/fish/vendor_completions.d/"
      # install -Dm644 "./completions/scm-engine.bash" "${pkgdir}/usr/share/bash-completion/completions/scm-engine"
      # install -Dm644 "./completions/scm-engine.zsh" "${pkgdir}/usr/share/zsh/site-functions/_scm-engine"
      # install -Dm644 "./completions/scm-engine.fish" "${pkgdir}/usr/share/fish/vendor_completions.d/scm-engine.fish"

      # man pages
      # install -Dm644 "./manpages/scm-engine.1.gz" "${pkgdir}/usr/share/man/man1/scm-engine.1.gz"

scoops:
  - repository:
      owner: jippi
      name: scoop-bucket
    directory: bucket
    homepage: https://github.com/jippi/scm-engine
    description: Make working with .env files easier
    license: MIT

nfpms:
  - id: packages_for_gemfury
    formats:
      - deb
      - rpm
    file_name_template: "{{ .ConventionalFileName }}"
    homepage: https://github.com/jippi/scm-engine
    description: |-
      Make working with .env files easier
    maintainer: Christian Winther <scm-engine@jippi.dev>
    license: MIT
    vendor: scm-engine
    bindir: /usr/bin
    section: utils
    contents:
      # - src: ./completions/scm-engine.bash
      #   dst: /usr/share/bash-completion/completions/scm-engine
      #   file_info:
      #     mode: 0644
      # - src: ./completions/scm-engine.fish
      #   dst: /usr/share/fish/vendor_completions.d/scm-engine.fish
      #   file_info:
      #     mode: 0644
      # - src: ./completions/scm-engine.zsh
      #   dst: /usr/share/zsh/vendor-completions/_scm-engine
      #   file_info:
      #     mode: 0644
      # - src: ./manpages/scm-engine.1.gz
      #   dst: /usr/share/man/man1/scm-engine.1.gz
      #   file_info:
      #     mode: 0644
      - src: ./LICENSE
        dst: /usr/share/doc/scm-engine/copyright
        file_info:
          mode: 0644
    deb:
      lintian_overrides:
        - statically-linked-binary
        - changelog-file-missing-in-native-package

  - id: other_packages
    formats:
      - apk
      - archlinux
    file_name_template: "{{ .ConventionalFileName }}"
    homepage: https://github.com/jippi/scm-engine
    description: |-
      Make working with .env files easier
    maintainer: Christian Winther <scm-engine@jippi.dev>
    license: MIT
    vendor: scm-engine
    bindir: /usr/bin
    section: utils
    contents:
      # - src: ./completions/scm-engine.bash
      #   dst: /usr/share/bash-completion/completions/scm-engine
      #   file_info:
      #     mode: 0644
      # - src: ./completions/scm-engine.fish
      #   dst: /usr/share/fish/vendor_completions.d/scm-engine.fish
      #   file_info:
      #     mode: 0644
      # - src: ./completions/scm-engine.zsh
      #   dst: /usr/share/zsh/vendor-completions/_scm-engine
      #   file_info:
      #     mode: 0644
      # - src: ./manpages/scm-engine.1.gz
      #   dst: /usr/share/man/man1/scm-engine.1.gz
      #   file_info:
      #     mode: 0644
      - src: ./LICENSE
        dst: /usr/share/doc/scm-engine/copyright
        file_info:
          mode: 0644

# snapcrafts:
#   - name_template: "{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
#     title: scm-engine
#     summary: Make .env file management easier
#     description: |
#       Make working with .env files easier
#     publish: true
#     license: MIT
#     grade: stable
#     disable: "{{ if .IsNightly }}true{{ end }}"

sboms:
  - artifacts: archive

signs:
  - cmd: cosign
    certificate: "${artifact}.pem"
    output: true
    artifacts: checksum
    args:
      - sign-blob
      - "--output-certificate=${certificate}"
      - "--output-signature=${signature}"
      - "${artifact}"
      - --yes

docker_signs:
  - cmd: cosign
    artifacts: manifests
    output: true
    args:
      - "sign"
      - "${artifact}@${digest}"
      - --yes

release:
  name_template: "v{{ .Version }}"
  prerelease: "auto"
  make_latest: true
  mode: append
  footer: |
    **Full Changelog**: https://github.com/jippi/scm-engine/compare/{{ .PreviousTag }}...{{ if .IsNightly }}nightly{{ else }}{{ .Tag }}{{ end }}

publishers:
  - name: gemfury
    dir: "{{ dir .ArtifactPath }}"
    ids:
      - packages_for_gemfury
    cmd: curl -s -F p1=@{{ .ArtifactName }} https://{{ .Env.FURY_PUSH_TOKEN }}@push.fury.io/jippi/
