# syntax=docker/dockerfile:1
# See https://hub.docker.com/r/docker/dockerfile

FROM ubuntu

RUN set -ex \
  && apt-get update \
  && apt-get install ca-certificates --yes \
  && apt-get clean

COPY ["scm-engine", "/usr/local/bin/scm-engine"]
