FROM squidfunk/mkdocs-material

# https://github.com/lukasgeiter/mkdocs-awesome-pages-plugin
RUN pip install mkdocs-awesome-pages-plugin
RUN pip install mkdocs-git-revision-date-localized-plugin
RUN pip install mkdocs-git-authors-plugin
