name: Grype

on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:

jobs:
  # ------------------------------

  scan-source:
    name: scan-source
    runs-on: ubuntu-latest

    permissions:
      security-events: write
      actions: read
      contents: read

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: anchore/scan-action@v3
        with:
          path: "."
          fail-build: true

  # ------------------------------
