name: Lint

on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:

permissions:
  # Required: allow read access to the content for analysis.
  contents: read

  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  pull-requests: read

  # Optional: Allow write access to checks to allow the action to annotate code in the PR.
  checks: write

jobs:
  # ------------------------------

  golangci-lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: go.mod
          cache: false

      - uses: arduino/setup-task@c0bc642852239c2689f73f4ea6459c29405f3c52 # v3.0.0
        with:
          # renovate: datasource=github-releases depName=go-task/task
          version: 3.53.1
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: setup
        run: task setup

      - name: golangci-lint
        uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9.3.0
        with:
          # renovate: datasource=github-releases depName=golangci/golangci-lint
          version: v2.12.2
          args: --timeout=5m

  # ------------------------------

  codeql-analyze:
    name: codeql-analyze
    runs-on: ubuntu-latest

    permissions:
      security-events: write
      actions: read
      contents: read

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: go.mod

      - uses: github/codeql-action/init@db488ddef3bf6cb639b32c2e9a7c0a7ea8271d28 # v4.37.8

      - uses: github/codeql-action/autobuild@db488ddef3bf6cb639b32c2e9a7c0a7ea8271d28 # v4.37.8

      - uses: github/codeql-action/analyze@db488ddef3bf6cb639b32c2e9a7c0a7ea8271d28 # v4.37.8

  # ------------------------------

  semgrep:
    runs-on: ubuntu-latest
    name: semgrep
    container:
      image: returntocorp/semgrep
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          repository: dgryski/semgrep-go
          path: rules

      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: go.mod

      - name: semgrep
        run: semgrep scan --error --enable-nosem -f ./rules .
