name: Security

on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  # ------------------------------

  govulncheck:
    runs-on: ubuntu-latest
    name: govulncheck
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: go.mod

      - uses: arduino/setup-task@c0bc642852239c2689f73f4ea6459c29405f3c52 # v3.0.0
        with:
          # renovate: datasource=github-releases depName=go-task/task
          version: 3.53.1
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: setup
        run: task setup

      - name: install govulncheck
        run: go install golang.org/x/vuln/cmd/govulncheck@latest

      - name: run govulncheck
        run: govulncheck ./...

  # ------------------------------

  gitleaks:
    runs-on: ubuntu-latest
    name: gitleaks
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - uses: gitleaks/gitleaks-action@e0c47f4f8be36e29cdc102c57e68cb5cbf0e8d1e # v3.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE}}
        if: ${{ env.GITLEAKS_LICENSE != '' }}

  # -----------------------------

  grype-scan:
    runs-on: ubuntu-latest
    name: grype-scan

    permissions:
      security-events: write
      actions: read
      contents: read

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: anchore/scan-action@27805bf3b4e84b4a5c980df22ed233c00390a439 # v7.4.2
        with:
          path: "."
          fail-build: true
          output-format: table
