name: Test

on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    name: go test
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: go.mod

      - name: setup-tparse
        run: go install github.com/mfridman/tparse@latest

      - uses: arduino/setup-task@c0bc642852239c2689f73f4ea6459c29405f3c52 # v3.0.0
        with:
          # renovate: datasource=github-releases depName=go-task/task
          version: 3.53.1
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: setup
        run: |
          task setup
          task build

      - name: test
        run: ./scripts/test.sh

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Ensure scm-engine binary work
        run: ./scm-engine -h

      - name: Test scm-engine against a GitLab project
        run: ./scm-engine gitlab evaluate all
        if: env.SCM_ENGINE_TOKEN
        env:
          SCM_ENGINE_TOKEN: "${{ secrets.GITLAB_INTEGRATION_TEST_API_TOKEN }}"
          SCM_ENGINE_CONFIG_FILE: ".scm-engine.gitlab.example.yml"
          GITLAB_PROJECT: "jippi/scm-engine-schema-test"
          GITLAB_BASEURL: https://gitlab.com/

      - name: Show any diff that may be in the project
        run: git diff
